CREATE DATABASE bancopidosguri;
\c bancopidosguri;

CREATE TABLE etc (
  id SERIAL PRIMARY KEY,
  nome VARCHAR(100)
);

INSERT INTO etc (nome) VALUES ('Pedro'), ('Luan'), ('Maria');


CREATE TABLE usuarios (
  id SERIAL PRIMARY KEY,
  nome VARCHAR(100) NOT NULL,
  email VARCHAR(100) UNIQUE NOT NULL,
  senha VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE recargas (
  id SERIAL PRIMARY KEY,
  usuario_id INTEGER NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
  local VARCHAR(200) NOT NULL,
  endereco VARCHAR(300) NOT NULL,
  data_hora TIMESTAMP NOT NULL,
  duracao VARCHAR(20) NOT NULL,
  energia DECIMAL(10, 2) NOT NULL,
  custo DECIMAL(10, 2) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
